### ISSUE TITLE
panic: runtime error:

### ISSUE THREAD

**Issue by venom26** [c3l3si4n/crtdumper#3]
Hey,
I hope you are doing well.

So I was running this tool on one of my server and I got below error. Do you know maybe why this happened or is this a bug?
I was running this with just `./crtdumper` command and when it exited because of this error it also did not create the resume file.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x777f74]

goroutine 66 [running]:
main.CreateLogClient.func1({0x8f1680?, 0xbddcc0?}, 0x0, {0x8eeba0?, 0xc00042d5c0?})
        /root/crtdumper/ct.go:74 +0xd4
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc000168780, 0xc00186baa0)
        /root/go/pkg/mod/github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:705 +0x315
github.com/hashicorp/go-retryablehttp.(*RoundTripper).RoundTrip(0xc000398a20, 0x8ee4c0?)
        /root/go/pkg/mod/github.com/hashicorp/go-retryablehttp@v0.7.7/roundtripper.go:47 +0x72
net/http.send(0xc00022c900, {0x8ee4c0, 0xc000398a20}, {0x1?, 0x5af3a9?, 0x0?})
        /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/net/http/client.go:259 +0x5e4
net/http.(*Client).send(0xc00042c390, 0xc00022c900, {0x9dd7d168d?, 0x120?, 0x0?})
        /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/net/http/client.go:180 +0x98
net/http.(*Client).do(0xc00042c390, 0xc00022c900)
        /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/net/http/client.go:724 +0x8dc
net/http.(*Client).Do(...)
        /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/net/http/client.go:590
golang.org/x/net/context/ctxhttp.Do({0x8f1680, 0xbddcc0}, 0x8341ba?, 0xc00022c7e0)
        /root/go/pkg/mod/golang.org/x/net@v0.26.0/context/ctxhttp/ctxhttp.go:27 +0xd9
github.com/google/certificate-transparency-go/jsonclient.(*JSONClient).GetAndParse(0xc000243220, {0x8f1680, 0xbddcc0}, {0x839bf9, 0x12}, 0xc000039b68, {0x79c4a0, 0xc00186ba88})
        /root/go/pkg/mod/github.com/google/certificate-transparency-go@v1.2.1/jsonclient/client.go:190 +0x59b
github.com/google/certificate-transparency-go/client.(*LogClient).GetRawEntries(0xc000243220, {0x8f1680, 0xbddcc0}, 0x4ccbf, 0x4ccd3)
        /root/go/pkg/mod/github.com/google/certificate-transparency-go@v1.2.1/client/getentries.go:41 +0x1ea
main.GetX509CertLogEntries(0xc000243220, 0x4ccbf, 0x4ccd3)
        /root/crtdumper/ct.go:28 +0x4e
main.ProcessLog(0x0?, 0xc0002f2000, 0xc00007c380)
        /root/crtdumper/processLog.go:74 +0x510
created by main.main in goroutine 1
        /root/crtdumper/crtdumper.go:39 +0x38b
```

Please do let me know.

Thank you

**Comment by c3l3si4n** [comment]
I will investigate and let you know.

**Comment by c3l3si4n** [comment]
I've released a update so that the script saves the progress file for every 10k certificates downloaded. This should help with the issue of you losing progress.

**Comment by venom26** [comment]
Hey,
yeah, already testing it out. And looks like its working. Thanks for the quick fix. :)
